### ISSUE TITLE
ROMB Battery returns value of 0 or 2147483648 when not available

### ISSUE THREAD

**Issue by usolved** [dangmocrang/check_idrac#12]
Hi,

thanks for this neat plugin.
Some issues I notices with the battery module.

**1.**
The web interface is giving me two batteries:
System Board CMOS Battery - Good  
PERC1 ROMB Battery - Good

I'm wondering why the plugin gives back PERC1 and 2 and the second with a "0"?
```
BATTERY
--System Board CMOS Battery: ENABLED/OK [PRESENCEDETECTED]
--PERC1 ROMB Battery: ENABLED/OK [PRESENCEDETECTED]
--PERC2 ROMB Battery: ENABLED/OK [0(!)]
```

I think this shouldn't be listed (or can I catch this state in the conf?)

**2.**
Another server but maybe the same issue:

Web interfaces just have:
System Board CMOS Battery - Good 

Plugin returns:
```
BATTERY
--System Board CMOS Battery: ENABLED/OK [PRESENCEDETECTED]
--PERC1 ROMB Battery: ENABLED/OK [-2147483648(!)]
--PERC2 ROMB Battery: ENABLED/OK [-2147483648(!)]
```

Regards
Ricardo

**Comment by dangmocrang** [comment]
Hi,

This is because your idrac return that snmp data so the scrtipt just catch
and translate the value to "presentdetected".

I dont know why your perc retuen with strange value so script can not
translate. Maybe your idrac version different from mine, i didn't know it
would have strange values.

If you dont want just dont check them or you can add "0" or "-2147..." to
OK state in conf file

Regards,
Dung

**Comment by usolved** [comment]
Thanks for your reply.
Ok, I'll add these values to the config.

You are right, a snmpwalk returns these two...

SNMPv2-SMI::enterprises.674.10892.5.4.600.50.1.7.1.2 = STRING: "PERC1 ROMB Battery"
SNMPv2-SMI::enterprises.674.10892.5.4.600.50.1.7.1.3 = STRING: "PERC2 ROMB Battery"

...but there's just one in the web interface.
Really strange :)

**Comment by mdecker** [comment]
I just ran into the same problem. snmpwalk shows

    IDRAC-MIB-SMIv2::systemBatteryChassisIndex.1.3 1
    IDRAC-MIB-SMIv2::systemBatteryIndex.1.3 3
    IDRAC-MIB-SMIv2::systemBatteryStateCapabilities.1.3 0
    IDRAC-MIB-SMIv2::systemBatteryStateSettings.1.3 enabled
    IDRAC-MIB-SMIv2::systemBatteryStatus.1.3 ok
    IDRAC-MIB-SMIv2::systemBatteryReading.1.3 0
    IDRAC-MIB-SMIv2::systemBatteryLocationName.1.3 "PERC2 ROMB Battery"

for a PERC that isn't there. Unfortunately I don't think that adding "0" to the OK state is  a good idea as it catches far too much and you will miss far too many errors (as soon as a "0" appears in any state it will be considered OK).
I have two identical iDRAC7 servers which do this. I suspect it depends on the system board: If that theoretically supports a 2nd PERC, then you run into this.
So far I could not come up with a clean solution. Maybe there has to be an "ignore" option for certain descriptors in the config file? This way you can selectively suppress certain components that report crap.

**Comment by dangmocrang** [comment]
Actually this script is not for global check like you are using. It used to
check individual device so to ignore you can simple not add that check
command with rom 2😂
On Apr 8, 2016 8:37 PM, "Michael Decker" <notifications@github.com> wrote:
>
> I just ran into the same problem. snmpwalk shows
>
> IDRAC-MIB-SMIv2::systemBatteryChassisIndex.1.3 1
> IDRAC-MIB-SMIv2::systemBatteryIndex.1.3 3
> IDRAC-MIB-SMIv2::systemBatteryStateCapabilities.1.3 0
> IDRAC-MIB-SMIv2::systemBatteryStateSettings.1.3 enabled
> IDRAC-MIB-SMIv2::systemBatteryStatus.1.3 ok
> IDRAC-MIB-SMIv2::systemBatteryReading.1.3 0
> IDRAC-MIB-SMIv2::systemBatteryLocationName.1.3 "PERC2 ROMB Battery"
>
> for a PERC that isn't there. Unfortunately I don't think that adding "0"
to the OK state is a good idea as it catches far too much and you will miss
far too many errors (as soon as a "0" appears in any state it will be
considered OK).
> I have two identical iDRAC7 servers which do this. I suspect it depends
on the system board: If that theoretically supports a 2nd PERC, then you
run into this.
> So far I could not come up with a clean solution. Maybe there has to be
an "ignore" option for certain descriptors in the config file? This way you
can selectively suppress certain components that report crap.

**Comment by mdecker** [comment]
Can you elaborate on how I would do what you propose? So far I understand you can check either all hardware or some specific component like "CPU" or "BATTERY". How could I exclude "PERC2 ROMB Battery" from my check? I could not find any way to do that so far.

**Comment by dangmocrang** [comment]
Ah you add a number after the device type like this

-w CPU#1
