### ISSUE TITLE
Specifying hardware number requires configuration file?

### ISSUE THREAD

**Issue by Jcpetrucci** [dangmocrang/check_idrac#13]
The example in MANUAL.md shows checking a specific DIMM and not using a configuration file, but when I try it states that I need to use a configuration file.

Check specific hardware
./idrac2.1.py -H 10.10.10.20 -v2c -c public -w MEM#3

**Comment by dangmocrang** [comment]
It seems that my mistake in manual, this case you need to use with state options for state threshold. Check specific hw will require state threshold to check against hw state, i.e: DIMM is OK or not...
