### ISSUE TITLE
iDRAC8 / Poweredge R930 / Threshold Erros

### ISSUE THREAD

**Issue by t3arj3rk3r** [dangmocrang/check_idrac#14]
Hi!
Great Plugin! Just one little problem: i am unable to define thresholds to receive perfdata on a Poweredge R930. Its not working at all. Here is an example from Temp-Sensor:

![screen shot 2015-11-05 at 14 01 25](https://cloud.githubusercontent.com/assets/12830302/10969013/e16c8178-83c5-11e5-94f8-33f2b384f4c1.png)

Any advice? Do you need further information?

Kind regards - P

**Comment by dangmocrang** [comment]
i will check and reply you soon!

**Comment by dangmocrang** [comment]
hmm... it seam you misunderstand the threshold.
--temp-warn should be 50,60 then --temp-crit must be 40,150. 
Try and see if error still occur.
