### ISSUE TITLE
iDRAC8 / Poweredge R930 / DISK ON(!)

### ISSUE THREAD

**Issue by t3arj3rk3r** [dangmocrang/check_idrac#15]
Hi!
DISK check is WARNING, because it returns ON(!). Can you implement that state? Atm I have the -n option activated...which is not best practice :D Or am I doing smth wrong?

![screen shot 2015-11-05 at 14 09 42](https://cloud.githubusercontent.com/assets/12830302/10969229/3ce643d0-83c7-11e5-8ddf-a1705a99379d.png)

Thank you! Great great Plugin!

**Comment by dangmocrang** [comment]
Hi,

You must use with option --ok to define which state is ok, on your case is
ON.
Best practice is to use plugin with config file. You will see sample state
definition in config file.

Regards,
Dung
