### ISSUE TITLE
Unable to use specific hardware such as FAN#1 in nagios config

### ISSUE THREAD

**Issue by jangras** [dangmocrang/check_idrac#17]
as nagios config file takes # as comment, i am unable to use # in specific hardware check such as FAN#1
./check_idrac -m /usr/share/snmp/mibs/idrac.mib -H <IP> -v2c -c @apfin@nce -w FAN#1
while defining service description in nagios config it takes # as comment. can we use "-" instead of "#"? Please reply.

**Comment by dangmocrang** [comment]
use [fan1] instead 😁

**Comment by dangmocrang** [comment]
i mentioned in sample config already

**Comment by jangras** [comment]
dear, using FAN1 it says "sorry, hardware not supported!" please help..

**Comment by dangmocrang** [comment]
Try use with command line and see if it work or not.
Can you pass command you ran and config content here?

**Comment by jangras** [comment]
Below is the full output of error, i am getting. please check the output of second command, when i am using FAN1, it says "sorry, hardware not supported!" please correct me if i am wrong. 

nagios:/usr/lib/nagios/plugins # ./check_idrac -H 10.10.10.10 -f test.conf -m /usr/share/snmp/mibs/idrac.mib -w FAN#1
OK - System Board Fan1A: 3720 RPM - ENABLED/OK

nagios:/usr/lib/nagios/plugins # ./check_idrac -H 10.10.10.10 -f test.conf -m /usr/share/snmp/mibs/idrac.mib -w FAN1
sorry, hardware not supported!

nagios:/usr/lib/nagios/plugins # cat test.conf
[snmp]
version = 2c
community = 'public'

[fan1]
thresholds =

[state]
OK = ok|online|spunup|full|ready|enabled|presence
WARN = $ALL$
CRIT = critical|nonRecoverable|fail

**Comment by jangras** [comment]
my service description in nagios for specific hardware is as below:

define service{
        use                     dell-service
        hostgroup_name          dell-devices
        service_description      FAN1
        check_command           check_idrac!FAN#1
        }
 
the FAN#1 option is being read as FAN only by nagios. what service description u suggest for specific hardware in nagios.

**Comment by jangras** [comment]
if i use full scan i am getting "SMTP timeout" but while running for specific hardware, it is able to show all component one by one.

**Comment by dangmocrang** [comment]
Hi,

Snmp timeout caused by your idrac is using old firmware version.

When i mentioned use [fan1] it is only in config file not the command. So
in command line keep fan#1

Regards,
Dung

**Comment by jangras** [comment]
Hi
First of all its latest firmware I am using. Second, I understood that i can use fan1 in config file. I am not talking about config file. My concern is to use fan#1 in commands.cfg and host.cfg file as # taken as a comment in these config files. hope u now understand my problem.

**Comment by dangmocrang** [comment]
ok, but i have nothing to do with SNMP Time out since it caused by idrac. About the config file I don't why your nagios made FAN#1 as comment, we are using this with no comment problem and not any one has this problem.

**Comment by dangmocrang** [comment]
More info: we are using Naigos 3 and 4. If you are using other version then Edit my script at line 273:

# verify hardware input
272:    if conf['hardware']:
273:        conf['hardware'] = conf['hardware'].split('#')
274:        try:

Now let's change it to any symbol you want ==> conf['hardware'] = conf['hardware'].split('-')

**Comment by jangras** [comment]
yes, that did the trick. thanks for the solution. I was searching for such solution only. Kudos to you.

**Comment by jangras** [comment]
Hi can u please tell me how to display plugin output comma separated as multiple lines output is not visible in nagios output, only first line is displayed.

**Comment by dangmocrang** [comment]
Ah, you must use in e.x fan#1 in nagios, group check is not designed for
production since it does not print the prefix like OK, CRiT, WARN

But if you want to, edit line 844 to:
```
print ';'.join(result)
```
