### ISSUE TITLE
Parser problem for PS

### ISSUE THREAD

**Issue by mikehubert4012** [dangmocrang/check_idrac#19]
Hi, 

When I remove power on a PS to test a critical problem, i get that a hardware not found. (PS#2)

/usr/lib/nagios/plugins/check_idrac.py -H 10.x.x.x -v2c -c public -w PS#1
OK - PS 1: OK, Volt I/O: 264 V/208 V, Current: 0.4 A, Watt I/O: 900.0 W/750 W

/usr/lib/nagios/plugins/check_idrac.py -H 10.x.x.x -v2c -c public -w PS#2
hardware not found! If you sure the hw exists then you may want to edit TRANSLATOR code (line 612).

/usr/lib/nagios/plugins/check_idrac.py -H 10.x.x.x -v2c -c public -w PS
PS 1: OK, Volt I/O: 264 V/208 V, Current: 0.4 A, Watt I/O: 900.0 W/750 W
PS 2: CRITICAL(!!), Volt I/O: 264 V/(N/A) V, Current: (N/A) A, Watt I/O: 900.0 W/750 W

I was able to correct this, but i think the solution is not permanent one. 
I added thoses lines at line 388: 

                if self.hardware[2] == 'PS' :
                    output = output.replace('No Such Instance currently exists at this OID','0')
                else:

That way I get a CRIT on PS#2. 
/usr/lib/nagios/plugins/check_idrac.py -H 10.x.x.x -v2c -c public -w PS#2
CRIT - PS 2: CRITICAL(!!), Volt I/O: 264 V/(N/A) V, Current: 0.0 A, Watt I/O: 900.0 W/750 W

Regards, 
Mike

**Comment by dangmocrang** [comment]
Hi,

When you remove the power its equal to the situation that you don't have
that power device, the script won't know if the device existed and be
removed or if its never exist before.

**Comment by mikehubert4012** [comment]
The problem is that when you call the snmpwalk manually from the snmp_cli string (see the request and answer for PS#1 and PS#2 below) 

<Power supply in a good state>
/etc/nagios/conf.d$ snmpget 10.x.x.x -O q -v 2c -c public powerSupplyIndex.1.1 powerSupplyStatus.1.1 powerSupplyOutputWatts.1.1 powerSupplyInputVoltage.1.1 powerSupplyRatedInputWattage.1.1 amperageProbeReading.1.1 -m ALL
IDRAC-MIB-SMIv2::powerSupplyIndex.1.1 1
IDRAC-MIB-SMIv2::powerSupplyStatus.1.1 ok
IDRAC-MIB-SMIv2::powerSupplyOutputWatts.1.1 7500
IDRAC-MIB-SMIv2::powerSupplyInputVoltage.1.1 264
IDRAC-MIB-SMIv2::powerSupplyRatedInputWattage.1.1 9000
IDRAC-MIB-SMIv2::amperageProbeReading.1.1 4

<Power supply with power disconnected>
/etc/nagios/conf.d$ snmpget 10.x.x.x -O q -v 2c -c public powerSupplyIndex.1.2 powerSupplyStatus.1.2 powerSupplyOutputWatts.1.2 powerSupplyInputVoltage.1.2 powerSupplyRatedInputWattage.1.2 amperageProbeReading.1.2 -m ALL
IDRAC-MIB-SMIv2::powerSupplyIndex.1.2 2
IDRAC-MIB-SMIv2::powerSupplyStatus.1.2 critical
IDRAC-MIB-SMIv2::powerSupplyOutputWatts.1.2 7500
IDRAC-MIB-SMIv2::powerSupplyInputVoltage.1.2 264
IDRAC-MIB-SMIv2::powerSupplyRatedInputWattage.1.2 9000
IDRAC-MIB-SMIv2::amperageProbeReading.1.2 No Such Instance currently exists at this OID

As you see, the information for this device is present, the "No Such Instance..." is only present for the amperage reading. The powerSupplyStatus is there. Since the script trap "No Such Instance..." globally, it generate an error. 

Suppose the power is removed accidentaly, you need to know that the server is in a critical state to take action.

Regards, 
Mike

**Comment by dangmocrang** [comment]
Ok i will check script logic later, i'm on rush for another task. Thanks
for your ideal.
