### ISSUE TITLE
No perf data?

### ISSUE THREAD

**Issue by ckozler** [dangmocrang/check_idrac#20]
Hi -

I cant seem to figure out why this does not output any type of perfdata which nagios can consume. I read that the --no-alert disables performance data but even the bare data output does not contain any performance data in the way nagios expects it. Nagios expects it as pipe delimeted (meaning the rest of data after | is the perfdata) and then tag valued pair (data_point=value_point) separated by white space to indicate what should be plotted

Did I miss something?

Thanks for your help! Awesome script overall!

**Comment by ckozler** [comment]
Here is example run:

The final string should be the perf data output

[root@host dell_monitors]# ./check_idrac -H  host -v2c -c public -m /root/.snmp/mibs/idrac-smiv2.mib -w FAN
System Board Fan1A: 4920 RPM - ENABLED/OK
System Board Fan1B: 4440 RPM - ENABLED/OK
System Board Fan2A: 4920 RPM - ENABLED/OK
System Board Fan2B: 4440 RPM - ENABLED/OK
System Board Fan3A: 4920 RPM - ENABLED/OK
System Board Fan3B: 4440 RPM - ENABLED/OK
System Board Fan4A: 4800 RPM - ENABLED/OK
System Board Fan4B: 4440 RPM - ENABLED/OK
System Board Fan5A: 4920 RPM - ENABLED/OK
System Board Fan5B: 4440 RPM - ENABLED/OK
System Board Fan6A: 4680 RPM - ENABLED/OK
System Board Fan6B: 4440 RPM - ENABLED/OK

Here is an example of IMM which outputs perf data and all fan data

[root@host ibm_imm_checks]# /usr/local/nagios/libexec/LOCAL/ibm_imm_checks/check_imm_fans 74.201.248.82
Fan 1A Tach = 52%
Fan 1B Tach = 36%
Fan 2A Tach = 53%
Fan 2B Tach = 34%
Fan 3A Tach = 100%
Fan 3B Tach = 100%
Fan 4A Tach = 100%
Fan 4B Tach = 100%
Fan 5A Tach = 59%
Fan 5B Tach = 40%
Fan 6A Tach = 58%
Fan 6B Tach = 43%
|Fan1=52%;;;; Fan2=36%;;;; Fan3=53%;;;; Fan4=34%;;;; Fan5=100%;;;; Fan6=100%;;;; Fan7=100%;;;; Fan8=100%;;;; Fan9=59%;;;; Fan10=40%;;;; Fan11=58%;;;; Fan12=43%;;;;

**Comment by ckozler** [comment]
Nevermind, found it with the -p switch

Thanks!

**Comment by dangmocrang** [comment]
Hi,

In group check script not return perf data. Please use with one device
check

Cheer,
