### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by shanekelasavie** [dangmocrang/check_idrac#23]
Hi, 

I'm seeing a timeout for one of my dracs for the Fan check when using the Check_iDRAC for DELL iDRAC found on https://exchange.nagios.org/directory/P ... AC/details.

# /usr/local/nagios/libexec/check_idrac_health -H 172.16.0.39 -v2c -c XXXXX
PS
--PS 1: OK, Volt I/O: 264 V/230 V, Current: 0.6 A, Watt I/O: 900.0 W/750 W
--PS 2: OK, Volt I/O: 264 V/230 V, Current: 0.2 A, Watt I/O: 900.0 W/750 W
SNMP timeout!

It's not exactly a timeout though, if I comment the out the elif statement that prints the 'SNMP timeout!', as shown below. I can see that values for the Fan check are actually found. Can you please help with this issue? 

def get_snmp(self, oids):
 cmd_v3 = '%s %s -O q -v %s -u %s -l %s -a %s -A %s -x %s -X %s %s -m %s'\
 % (self.snmp_command, self.host, conf['snmp_version'], conf['snmp_security_name'],
 conf['snmp_security_level'],
 conf['snmp_authentication_protocol'], conf['snmp_authentication_password'],
 conf['snmp_privacy_protocol'], conf['snmp_privacy_password'],
 oids, self.mib_file)
 cmd_v2 = '%s %s -O q -v %s -c %s %s -m %s' \
 % (self.snmp_command, self.host, conf['snmp_version'],
 conf['snmp_community'],
 oids, self.mib_file)
 available_cmd = {'3': cmd_v3, '2c': cmd_v2}
 snmp_cli = available_cmd[conf['snmp_version']]
 status, output = run(snmp_cli) # query snmp data
 if status != 0:
 if 'Unknown Object Identifier' in output:
 print 'your MIB may out of dated!'
 print 'error -', output.replace('\n', '. ')
 #elif 'Timeout:' in output:
 # print 'SNMP timeout!'
 else:
 print output
 sys.exit(1)

IDRAC-MIB-SMIv2::coolingDeviceReading.1.1 3720
IDRAC-MIB-SMIv2::coolingDeviceReading.1.2 3840
IDRAC-MIB-SMIv2::coolingDeviceReading.1.3 3840
IDRAC-MIB-SMIv2::coolingDeviceReading.1.4 3720
IDRAC-MIB-SMIv2::coolingDeviceReading.1.5 3720
IDRAC-MIB-SMIv2::coolingDeviceReading.1.6 3840
IDRAC-MIB-SMIv2::coolingDeviceReading.1.7 3840
IDRAC-MIB-SMIv2::coolingDeviceReading.1.8 2400
IDRAC-MIB-SMIv2::coolingDeviceReading.1.9 2400
IDRAC-MIB-SMIv2::coolingDeviceReading.1.10 2400
IDRAC-MIB-SMIv2::coolingDeviceReading.1.11 2280
IDRAC-MIB-SMIv2::coolingDeviceReading.1.12 2280
IDRAC-MIB-SMIv2::coolingDeviceReading.1.13 2400
IDRAC-MIB-SMIv2::coolTimeout: No Response from 172.16.0.39
ingDeviceReading.1.14 2280
IDRAC-MIB-SMIv2::coolingDeviceType.1.1 coolingDeviceTypeIsAFan
IDRAC-MIB-SMIv2::coolingDeviceType.1.2 coolingDeviceTypeIsAFan
IDRAC-MIB-SMIv2::coolingDeviceType.1.3 coolingDeviceTypeIsAFan
IDRAC-MIB-SMIv2::coolingDeviceType.1.4 coolingDeviceTypeIsAFan
IDRAC-MIB-SMIv2::coolingDeviceType.1.5 coolingDeviceTypeIsAFan
IDRAC-MIB-SMIv2::coolingDeviceType.1.6 coolingDeviceTypeIsAFan
IDRAC-MIB-SMIv2::coolingDeviceType.1.7 coolingDeviceTypeIsAFan
IDRAC-MIB-SMIv2::coolingDeviceType.1.8 coolingDeviceTypeIsAFan
IDRAC-MIB-SMIv2::coolingDeviceType.1.9 coolingDeviceTypeIsAFan
IDRAC-MIB-SMIv2::coolingDeviceType.1.10 coolingDeviceTypeIsAFan
IDRAC-MIB-SMIv2::coolingDeviceType.1.11 coolingDeviceTypeIsAFan
IDRAC-MIB-SMIv2::coolingDeviceType.1.12 coolingDeviceTypeIsAFan
IDRAC-MIB-SMIv2::coolingDeviceType.1.13 coolingDeviceTypeIsAFan
IDRAC-MIB-SMIv2::coolingDeviceType.1.14 coolingDeviceTypeIsAFan

**Comment by dangmocrang** [comment]
There is line say that no response from your device....

**Comment by shanekelasavie** [comment]
Can you please explain how to resolve this?

**Comment by dangmocrang** [comment]
Upgrade your firmware may fix this
