### ISSUE TITLE
output problems

### ISSUE THREAD

**Issue by eric-b-hymowitz** [dangmocrang/check_idrac#25]
Greetings.

I'm having trouble with the output of the check_idrac plugin.

The output and the performance data are not formatted correctly.  According to https://nagios-plugins.org/doc/guidelines.html , the output should look like this:

SERVICE STATUS: text of output | performance data

However, the check_idrac plugin output looks like this:

System Board Inlet Temp: 23.0 C ENABLED/OK | Temperature=23.0;;;;
CPU1 Temp: 53.0 C ENABLED/OK | Temperature=53.0;;;;
CPU2 Temp: 46.0 C ENABLED/OK | Temperature=46.0;;;;

Nagios is not interpreting the output correctly, and this is causing problems.

Can you please look into this and adjust the output to match the Nagios plugin standards?

**Comment by dangmocrang** [comment]
Hi,

This already nagios perf format -> 'label'=value[UOM];[warn];[crit];[min];[max]
