### ISSUE TITLE
Show more information in the "Status Information" field

### ISSUE THREAD

**Issue by FlorianMiesenberger** [dangmocrang/check_idrac#28]
Dear @dangmocrang!

Thanks for your great job creating and maintaining this awsome check.
In my setup it is always showing "PS" (first line of output of script) - as you see in the screenshots.

![ok](https://cloud.githubusercontent.com/assets/6874610/18167217/a81fb094-704f-11e6-8389-79eef69144b6.png)
![crit](https://cloud.githubusercontent.com/assets/6874610/18167216/a81dc3b0-704f-11e6-9e02-aedb48d66f4e.png)
![crit-with-details](https://cloud.githubusercontent.com/assets/6874610/18167218/a820a7ec-704f-11e6-8891-98d4f1b984fb.png)

My question:
**Is there a way to show more information in the "Status Information" field when there is an error with hardware?** 

My Nagios configuration - commands.cfg:

```
# 'check_idrac_full' command definition
define command{
        command_name       check_idrac_full
        command_line           /usr/local/nagios/libexec/check_idrac/idrac_2.2rc4 -H $HOSTADDRESS$ -f /usr/local/nagios/libexec/check_idrac/idrac_2.1.conf -m /usr/local/nagios/libexec/check_idrac/idrac-smiv2.mib
        }
```

My Nagios configuration - hosts.cfg:

```
define service{
        use                                  generic-service
        host_name                      dell
        service_description          iDRAC Full
        check_command             check_idrac_full
        notifications_enabled       0
        }
```

Thank you and greeeeetz from Austria,
Florian Miesenberger

**Comment by dangmocrang** [comment]
I don't understand what info do you need to show?

**Comment by VincentROLLAND** [comment]
Hi guys,

Thank you for this great monitoring script, i have the same request than Florian, in most monitoring engine (nagios, centreon,...) we see in the interface only the fisrt line of the output, it will be cool to make an option for have a condensed output on one line, like this:

OK -- PS: OK, FAN: OK, BATTERY: OK, PU: OK, MEM: OK, VDISK: OK,....
KO -- PS: OK, FAN: OK, BATTERY: OK, PU: OK, MEM: OK, VDISK: KO,....
 
The extended inforation is the 2nd line : 

KO -- PS: OK, FAN: OK, BATTERY: OK, PU: OK, MEM: OK, VDISK: KO,....
--VDisk 1 (Virtual Disk0): KO/DEGRADED, RAID-1 (278.88 GB), BadBlock: 0 [Virtual Disk 0 on Integrated RAID Controller 1]

Regards

**Comment by dangmocrang** [comment]
Actually the script was mean to be used for single device per command :) Sorry for that
