### ISSUE TITLE
Memory alert

### ISSUE THREAD

**Issue by macdutra** [dangmocrang/check_idrac#30]
Hi guys,

I have the DIMM Socket B6 with status NONCRITICAL and I don't receive any alert, bellow the result, I'm using the new version 2.2rc4.

Memory 1 (DIMM Socket A1) 8.0 GB/1333 MHz: ENABLED/OK [DDR3, Kingston, S/N: D2268486]
Memory 2 (DIMM Socket A2) 8.0 GB/1333 MHz: ENABLED/OK [DDR3, Kingston, S/N: B8267986]
Memory 3 (DIMM Socket A3) 8.0 GB/1333 MHz: ENABLED/OK [DDR3, Kingston, S/N: CD268D86]
Memory 4 (DIMM Socket A4) 8.0 GB/1333 MHz: ENABLED/OK [DDR3, Kingston, S/N: CA267D86]
Memory 5 (DIMM Socket A5) 8.0 GB/1333 MHz: ENABLED/OK [DDR3, Kingston, S/N: CE268186]
Memory 6 (DIMM Socket A6) 8.0 GB/1333 MHz: ENABLED/OK [DDR3, Kingston, S/N: CE267E86]
Memory 7 (DIMM Socket A7) 8.0 GB/1333 MHz: ENABLED/OK [DDR3, Kingston, S/N: CE226FB9]
Memory 8 (DIMM Socket A8) 8.0 GB/1333 MHz: ENABLED/OK [DDR3, Kingston, S/N: CE226EB9]
Memory 9 (DIMM Socket B1) 8.0 GB/1333 MHz: ENABLED/OK [DDR3, Kingston, S/N: D2268F86]
Memory 10 (DIMM Socket B2) 8.0 GB/1333 MHz: ENABLED/OK [DDR3, Kingston, S/N: D1268286]
Memory 11 (DIMM Socket B3) 8.0 GB/1333 MHz: ENABLED/OK [DDR3, Kingston, S/N: 2826E089]
Memory 12 (DIMM Socket B4) 8.0 GB/1333 MHz: ENABLED/OK [DDR3, Kingston, S/N: CD267D86]
Memory 13 (DIMM Socket B5) 8.0 GB/1333 MHz: ENABLED/OK [DDR3, Kingston, S/N: CA268386]
Memory 14 (DIMM Socket B6) 8.0 GB/1333 MHz: ENABLED/NONCRITICAL [DDR3, Kingston, S/N: CD267986]
Memory 15 (DIMM Socket B7) 8.0 GB/1333 MHz: ENABLED/OK [DDR3, Kingston, S/N: CF267C86]
Memory 16 (DIMM Socket B8) 8.0 GB/1333 MHz: ENABLED/OK [DDR3, Kingston, S/N: D1267A86]

Regards,

Marcos Dutra

**Comment by dangmocrang** [comment]
Hi,

You must add that Noncritical to config file. I can guess all status possible, it depend on firmware version
