### ISSUE TITLE
Using -v2c public for snmpwalk calls

### ISSUE THREAD

**Issue by sadsfae** [dangmocrang/check_idrac#31]
Thank you for making this plugin and putting it all together.

Can I use  the equivalent of ```-v2c public``` ?

I get the following errors specifying this in the configuration file

```
[snmp]
version = '2c'
community = 'public'
```

This is the error I get in Nagios:

```
iDRAC Server Health;WARNING;notify-service-by-email;snmp version "None" is not supported!
```

When I run this manually and append -v2c everything works however - e.g.

```
/usr/lib64/nagios/plugins/idrac_2.2rc4 -H 10.12.64.131 -v2c -c public -m /usr/share/snmp/mibs/idrac-smiv2.mib
```

I've also tried ```version = '2'``` to no avail.

I see it's unset here in the code: https://github.com/dangmocrang/check_idrac/blob/master/idrac_2.2rc4#L17 but seems ugly to force it there, I'd like to use the config file you are shipping.

What am I doing wrong?

**Comment by sadsfae** [comment]
I am also omitting the configuration file completely and still get the same error:

e.g.

```
 /usr/lib64/nagios/plugins/idrac_2.2rc4 -H $HOSTADDRESS -v 2c -c public -m /usr/share/snmp/mibs/idrac-smiv2.mib --warn '$ALL$' --crit 'critical|nonRecoverable|fail' --ok 'ok|online|on|spunup|full|ready|enabled|presence'
```

Nagios says:

```
Current Status:	WARNING  (for 0d 1h 0m 45s)
Status Information:	snmp version "None" is not supported!
```

**Comment by sadsfae** [comment]
Ok, the issue is on my end and it was simple.  I simply forgot the trailing ```$``` on ```$HOSTADDRESS$```

**Comment by dangmocrang** [comment]
Hi,

That sound great! Sorry for late reply cause you msg me in the mid night
(in my country)

Have a nice day!

Dung
