### ISSUE TITLE
Return warning for NONCRITICAL error

### ISSUE THREAD

**Issue by nmore123** [dangmocrang/check_idrac#32]
Hi,

Is it possible to add WARNING when a NONCRITICAL error occur?

Via iDRAC I found "Correctable memory error rate exceeded for DIMM_B12".
This is reported via this script as:
Memory 24 (DIMM Socket B12) 32.0 GB/1333 MHz: ENABLED/NONCRITICAL [DDR3, Hynix Semiconductor, S/N: 318E5BCD]

But the exit code is still 0 and a status OK is returned in Nagios, I would like to see this as a WARNING state.

Thanks for a great plugin

**Comment by dangmocrang** [comment]
Hi,

It is possible. You can add that "NONCRITICAL" string into WARN section of
config file :)

Regards,
Dung

**Comment by nmore123** [comment]
Thanks for the reply. Works as a charm!

Cheers!
