### ISSUE TITLE
MEM checks 

### ISSUE THREAD

**Issue by johnsavvaidis** [dangmocrang/check_idrac#38]
Hello,

Many thanks for this script. It saved us to monitoring ESXis with different version threw Nagios.
Everything is working fine, but i noticed a small bug.
All files are the default files from git, also i have the latest version. 

In one server , there is a warning for Correctable memory error . The check finds that the RAM Dimm is in NONCRITICAL state, but it reports as OK.
In other servers, when a component is in NONCRITICAL, for example, ROM Battery, then the Nagios check is in Warning state. 

[root@lhvmsrv120 check_idrac-master]# /usr/lib64/nagios/plugins/check_idrac-master/idrac_2.2rc4 -H 10.168.2.64 -v 2c -c public -m /usr/lib64/nagios/plugins/check_idrac-master/idrac-smiv2.mib -w MEM#6
OK - Memory 6 (DIMM Socket A6) 32.0 GB/2133 MHz: ENABLED/NONCRITICAL [26, Hynix Semiconductor, S/N: 10CAA11A]

Can you please check ?

Thank you,
John

**Comment by dangmocrang** [comment]
hmm... I can't. The output is based MIB version of my devices. So if you use MIB file in this git repo it may result in different status. You must edit the script to suit your case.

**Comment by toconspiracy** [comment]
I guess you jumped into the same Problem as i fixxed in #39, try the merged script.
