### ISSUE TITLE
EMPTY values output

### ISSUE THREAD

**Issue by iovcho** [dangmocrang/check_idrac#4]
Hello there.
I have a problem with using this script.
------------------------------------------------------------------------------------------
[root@localhost check_idrac-master]# ./idrac_2.0b7 -H localhost -c public
PS
--
FAN
--
BATTERY
--
PU
--
MEM
--
VDISK
--
DISK
--
SENSOR
--
CPU
--
------------------------------------------------------------------------------------------

Somebody can help with this issue ?
Thanks,

**Comment by dangmocrang** [comment]
Hi fire,

First this script is used for idrac 7. Other with difference mib may not work properly. 
Second verify if you installed net-SNMP package.

Regards

-----Original Message-----

**Comment by iovcho** [comment]
Hello there. Thank you very much for fast reply.

Yes, I use idrac 7 on my server (Dell PE R420).
Here is the installed packages:
net-snmp-libs-5.5-50.el6_6.1.x86_64
net-snmp-5.5-50.el6_6.1.x86_64

idrac 7 information:
(Firmware Version 1.30.30 (Build 43))

Do you have any other suggestions?

Best regards,

**Comment by dangmocrang** [comment]
Hi fire,

If so. Please check if you are using python version 2.6 or above. Then try query SNMP by command snmpwalk to check if you can get the result from that.

#snmpwalk ip -v 2c -c public

Regards,

-----Original Message-----

**Comment by iovcho** [comment]
snmpwalk localhost -v 2c -c public
SNMPv2-MIB::sysDescr.0 = STRING: Linux localhost.domain.com 2.6.32-504.12.2.el6.x86_64 #1 SMP Wed Mar 11 22:03:14 UTC 2015 x86_64
SNMPv2-MIB::sysObjectID.0 = OID: NET-SNMP-MIB::netSnmpAgentOIDs.10
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (615136) 1:42:31.36
SNMPv2-MIB::sysContact.0 = STRING: Root <server@localhost.com> (configure /etc/snmp/snmpd.conf)
SNMPv2-MIB::sysName.0 = STRING: localhost.domain.com
SNMPv2-MIB::sysLocation.0 = STRING: Unknown (edit /etc/snmp/snmpd.conf)
SNMPv2-MIB::sysORLastChange.0 = Timeticks: (8) 0:00:00.08
SNMPv2-MIB::sysORID.1 = OID: SNMP-MPD-MIB::snmpMPDMIBObjects.3.1.1
SNMPv2-MIB::sysORID.2 = OID: SNMP-USER-BASED-SM-MIB::usmMIBCompliance
SNMPv2-MIB::sysORID.3 = OID: SNMP-FRAMEWORK-MIB::snmpFrameworkMIBCompliance
SNMPv2-MIB::sysORID.4 = OID: SNMPv2-MIB::snmpMIB
SNMPv2-MIB::sysORID.5 = OID: TCP-MIB::tcpMIB
SNMPv2-MIB::sysORID.6 = OID: IP-MIB::ip
SNMPv2-MIB::sysORID.7 = OID: UDP-MIB::udpMIB
SNMPv2-MIB::sysORID.8 = OID: SNMP-VIEW-BASED-ACM-MIB::vacmBasicGroup
SNMPv2-MIB::sysORDescr.1 = STRING: The MIB for Message Processing and Dispatching.
SNMPv2-MIB::sysORDescr.2 = STRING: The MIB for Message Processing and Dispatching.
SNMPv2-MIB::sysORDescr.3 = STRING: The SNMP Management Architecture MIB.
SNMPv2-MIB::sysORDescr.4 = STRING: The MIB module for SNMPv2 entities
SNMPv2-MIB::sysORDescr.5 = STRING: The MIB module for managing TCP implementations
SNMPv2-MIB::sysORDescr.6 = STRING: The MIB module for managing IP and ICMP implementations
SNMPv2-MIB::sysORDescr.7 = STRING: The MIB module for managing UDP implementations
SNMPv2-MIB::sysORDescr.8 = STRING: View-based Access Control Model for SNMP.
SNMPv2-MIB::sysORUpTime.1 = Timeticks: (8) 0:00:00.08
SNMPv2-MIB::sysORUpTime.2 = Timeticks: (8) 0:00:00.08
SNMPv2-MIB::sysORUpTime.3 = Timeticks: (8) 0:00:00.08
SNMPv2-MIB::sysORUpTime.4 = Timeticks: (8) 0:00:00.08
SNMPv2-MIB::sysORUpTime.5 = Timeticks: (8) 0:00:00.08
SNMPv2-MIB::sysORUpTime.6 = Timeticks: (8) 0:00:00.08
SNMPv2-MIB::sysORUpTime.7 = Timeticks: (8) 0:00:00.08
SNMPv2-MIB::sysORUpTime.8 = Timeticks: (8) 0:00:00.08
HOST-RESOURCES-MIB::hrSystemUptime.0 = Timeticks: (8579301) 23:49:53.01
HOST-RESOURCES-MIB::hrSystemUptime.0 = No more variables left in this MIB View (It is past the end of the MIB tree)

**Comment by dangmocrang** [comment]
Hi,

Hmm. Check back first mail and saw that you forgot to call option "-m". Try that with mib file on git.

# ./idrac_2.0b7 -H localhost -c public -m [path to mib file]


Regards,
Dung

-----Original Message-----

**Comment by iovcho** [comment]
[root@localhost check_idrac-master]# ./idrac_2.0b7 -H localhost -c public -m /root/check_idrac-master/idrac-smiv2.mib 
PS
--
FAN
--
BATTERY
--
PU
--
MEM
--
VDISK
--
DISK
--
SENSOR
--
CPU
--
[root@localhost check_idrac-master]#

**Comment by dangmocrang** [comment]
Hi,

One question:
Is that "localhost" your hostname you used in the command or just for email me?

Regards,
Dung

-----Original Message-----

**Comment by iovcho** [comment]
The SNMP listen only on 127.0.0.1 and snmpwalk works on localhost, but the server's hostname is different. Do you the real hostname is "nagios" and full name "nagios.mydomain.com"

**Comment by dangmocrang** [comment]
Hi,

I might know what happen with your case. From SNMP output I saw you queried to a Linux server not a idrac device.
This script must be used on idrac device directly. You must enable SNMP on idrac first via its ui. Then point the script direct to idrac not the server you installed on it.

Regards,
Dung

-----Original Message-----

**Comment by iovcho** [comment]
Hi again! Now everything Works! Thank you very very much for yours help! 
Here is the output:
[root@localhost check_idrac-master]# ./idrac_2.0b7 -H IDRAC7_IPADDRESS -c public -m /root/check_idrac-master/idrac-smiv2.mib 
PS
--PS 1: OK, Volt I/O: 264 V/(N/A) V, Current: 0.2 A, Watt I/O: 666.0 W/550.0 W
--PS 2: OK, Volt I/O: 264 V/(N/A) V, Current: 5.6 A, Watt I/O: 666.0 W/550.0 W
FAN
--
BATTERY
--System Board CMOS Battery: ENABLED/OK [PRESENCEDETECTED]
PU
--PU 1: ENABLED/OK, RedundancyStatus: FULL, SystemBoard Pwr Consumption: 56 W
MEM
--Memory 1 (DIMM Socket A1) 8.0 GB/1600 MHz: ENABLED/OK [DDR3, Nanya Technology, S/N: XXXXXXXX]
--Memory 2 (DIMM Socket A2) 8.0 GB/1600 MHz: ENABLED/OK [DDR3, Nanya Technology, S/N: YYYYYYYY]
VDISK
--VDisk 1 (Virtual Disk 0): OK/ONLINE, RAID-1 (465.25 GB), BadBlock: 0 [Virtual Disk 0 on Integrated RAID Controller 1]
DISK
--PDisk 1 (0:1:0) 465.25 GB: ONLINE, PowerStat: SPUNUP, HotSpare: no [ATA, S/N: XXXXXXXX]
--PDisk 2 (0:1:1) 465.25 GB: ONLINE, PowerStat: SPUNUP, HotSpare: no [ATA, S/N: YYYYYYYY]
SENSOR
--System Board Inlet Temp: 26.0 C ENABLED/OK
--CPU1 Temp: 48.0 C ENABLED/OK
CPU
--CPU 1 (4 cores/4 threads): ENABLED/OK [Intel(R) Xeon(R) CPU E5-2407 0 @ 2.20GHz]

**Comment by dangmocrang** [comment]
Cheer!

Regards
Dung

-----Original Message-----

**Comment by iovcho** [comment]
One more question. Now works, but I not have output for FAN, parameters:


For Power Supply works:
[root@localhost check_idrac-master]# ./idrac_2.0b7 -H IDRAC7_IPADDRESS-c public -m /root/check_idrac-master/idrac-smiv2.mib -w FAN

[root@localhost check_idrac-master]# ./idrac_2.0b7 -H IDRAC7_IPADDRESS -c public -m /root/check_idrac-master/idrac-smiv2.mib -w PS
PS 1: OK, Volt I/O: 264 V/(N/A) V, Current: 0.2 A, Watt I/O: 666.0 W/550.0 W
PS 2: OK, Volt I/O: 264 V/(N/A) V, Current: 5.6 A, Watt I/O: 666.0 W/550.0 W

**Comment by dangmocrang** [comment]
Hi,

This may because your idrac has problem with output SNMP for fan, try with other and see if it work or not. Mine used to. I upgrade firmware to new  version and it fixed.

Regards,
Dung

-----Original Message-----
