### ISSUE TITLE
Handeling of DEGRADED vDisk

### ISSUE THREAD

**Issue by machtunder** [dangmocrang/check_idrac#5]
First of all thanks for the plugin!  
We're trying to implement it in our environment, but currently hit a dead end with the monitoring part for storage system. 
We’re using a RAID 1 configuration for our System Disk and if one Disk is removed or faulted it should show up as a Critical event. 
But in our tests the result we’ve got after removing one of the two disks is only that it is non critical and the system neither logs a warning nor a critical state. 
Is there a way to set the alert threshold in a way so that a disk failing, or being removed triggers a warning? 
Thank you. 
Best Regards!

**Comment by dangmocrang** [comment]
Hi,

Please show me your check command and the output on your monitoring system

Regards
Dung

**Comment by machtunder** [comment]
Hi,

My check command:

command_line $USER1$/check_idrac --host $ARG1$ --conf $USER1$/check_idrac.conf --hardware $ARG2$ --perf

My Command File:

#SNMP CONFIGURATIONS
SNMP_version = 2c
SNMP_community = 'xy'
#SNMP_v3_user = 'my user'
#SNMP_v3_security_level = noAuthNoPriv|authNoPriv|authPriv
#SNMP_v3_security_level = authPriv
#SNMP_v3_authentication_protocol = sha|md5
#SNMP_v3_authentication_protocol = sha
#SNMP_v3_authentication_password = 'mypassword'
#SNMP_v3_privacy_protocol = des|aes
#SNMP_v3_privacy_protocol = aes
#SNMP_v3_privacy_password = 'mypassword'

#STATE ALERT
#You can use state alert with option --ok/--warn/--crit as well.
#User can defines state alert based on device status
#Conditions are separated by "|"
#$ALL$ means all status that not belong to others.
#OK = $ALL$ means --no-alert
OK = ok|online|spunup|full|ready|enabled|presence
WARN = $ALL$
CRIT = critical|nonRecoverable|fail

Best Regards

**Comment by dangmocrang** [comment]
Hi,

Please include with real parameter you put in --hardware option. And I need
to know the output to know what is going on.

Regards
Dung

**Comment by machtunder** [comment]
Hi the real Parameter:
check_command		check_idrac!10.x.x.x!vdisk

command_line /usr/local/icinga/lib/check_idrac --host 10.x.x.x --conf /usr/local/icinga/lib/check_idrac.conf --hardware vdisk --perf

**Comment by dangmocrang** [comment]
Hi,

I see. You just put "vdisk" in --hardware option, which will only trigger
the script to work in scan mode.
You must add the number of the vdisk for the script to check it
individually.

Assuming you have two "vdisk". Then this command will check second vdisk:

 /usr/local/icinga/lib/check_idrac --host 10.x.x.x --conf
/usr/local/icinga/lib/check_idrac.conf --hardware vdisk#2 --perf

Regards
Dung

**Comment by machtunder** [comment]
Oh... 

Big Big Thx now it works perfect!
