### ISSUE TITLE
Issue with PS check

### ISSUE THREAD

**Issue by bmeneuvrier** [dangmocrang/check_idrac#6]
Hi Dung,
Thanks for your great job regarding this check.
I met some issues with PS check on differents servers (2 x PE R420, 1 x PE R720, 2 x PE R620, 2 x PE R630, 2 x PE R430).
Let's have a look to a PE R630:
root@srv020:/usr/lib/nagios/plugins# ./check_idrac -H srv001-idrac -m ./idrac-smiv2.mib -c public -w PS -f check_idrac.conf
PS 1: OK, Volt I/O: 264 V/(N/A) V, Current: 0.6 A, Watt I/O: 594.0 W/495.0 W
PS 2: OK, Volt I/O: 264 V/(N/A) V, Current: 0.2 A, Watt I/O: 594.0 W/495.0 W
root@srv020:/usr/lib/nagios/plugins# ./check_idrac -H srv001-idrac -m ./idrac-smiv2.mib -c public -w PS#1 -f check_idrac.conf
CRIT - PS 1: OK, Volt I/O: 264 V/0(!!) V, Current: 0.6(!!) A, Watt I/O: 594.0 W/495(!!) W
root@srv020:/usr/lib/nagios/plugins# ./check_idrac -H srv001-idrac -m ./idrac-smiv2.mib -c public -w PS#2 -f check_idrac.conf
CRIT - PS 2: OK, Volt I/O: 264 V/0(!!) V, Current: 0.2(!!) A, Watt I/O: 594.0 W/495(!!) W

My  check_idrac.conf is the default one. Why does it quit with Critical status whereas the comment is OK?
I got this result with each server. The check runs on Debian Wheezy with Python 2.7.3

Thanks for your help.

Bruno

**Comment by dangmocrang** [comment]
Hi Bruno,

With default config there is no threshold set for current and wat. That why the script return with critical.
Just look at the "!!". They mean current and wat value are over the default threshold. 
PS1:OK is just the status of the power supply.

So check "--help" to know how to set threshold for current and load

Regards
Dung


-----Original Message-----

**Comment by bmeneuvrier** [comment]
Hi Dung,
Here is what I get when I set some thresholds:
./check_idrac -H srv001-idrac -m ./idrac-smiv2.mib -c public -w PS#1 -f check_idrac.conf --volt-warn=220,230 --volt-crit=200,219 --cur-warn=1,1.5 --cur-crit=1.6,2 --wat-warn=800,850 --wat-crit=850,900
CRIT - PS 1: OK, Volt I/O: 264 V/0(!!) V, Current: 0.6(!!) A, Watt I/O: 594.0 W/495(!!) W
It seems they are not used. Where am I wrong?

Thanks,

Bruno


De : Nguyen Duc Trung Dung <notifications@github.com<mailto:notifications@github.com>>
Répondre à : dangmocrang/check_idrac <reply@reply.github.com<mailto:reply@reply.github.com>>
Date : mardi 23 juin 2015 14:15
À : dangmocrang/check_idrac <check_idrac@noreply.github.com<mailto:check_idrac@noreply.github.com>>
Cc : Bruno Meneuvrier <bruno.meneuvrier@ioxar.fr<mailto:bruno.meneuvrier@ioxar.fr>>
Objet : Re: [check_idrac] Issue with PS check (#6)

Hi Bruno,

With default config there is no threshold set for current and wat. That why the script return with critical.
Just look at the "!!". They mean current and wat value are over the default threshold.
PS1:OK is just the status of the power supply.

So check "--help" to know how to set threshold for current and load

Regards
Dung


-----Original Message-----

**Comment by dangmocrang** [comment]
Hi Bruno,

Something not right here,I will check and reply to you very soon.

Regards,
Dung

-----Original Message-----

**Comment by dangmocrang** [comment]
Hi Bruno,

From your output I found a bug in my script when output Voltage value when checking individual PS. I fixed it in version 2.0b8.

And the reason the threshold not working right because you have misunderstand it. 
Example: --volt-warn=[min,max] and --volt-crit=[min,max]. This means:

MINCRIT=<MINWARN=<NORMAL=<MAXWARN=<MAXCRIT

So this should be: --volt-warn=220.231 --volt-crit=200,240

Regards,
Dung

**Comment by dangmocrang** [comment]
Hi,

Did you get my reply on github? Your issues fixed?

Regards,
Dung

-----Original Message-----

**Comment by bmeneuvrier** [comment]
Dung,
I got your reply and I tested it. Many thanks to react so quickly. You got the point regarding my mistake. It's now working on most of my servers. Nevertheless, one PowerEdge R430 is running differently. At one time, only one PS is alive, the second is in standby state. So the current is 0 A. Look at plugin behavior:
root@srv020:/usr/lib/nagios/plugins# ./check_idrac -H srv005-idrac -m ./idrac-smiv2.mib -c public -w PS#2 -f check_idrac.conf --volt-warn=0,230 --volt-crit=0,270 --cur-warn=0,1.5 --cur-crit=0,2 --wat-warn=450,800 --wat-crit=400,900
CRIT - PS 2: OK, Volt I/O: 264 V/0(!!) V, Current: 0.0(!!) A, Watt I/O: 666.0 W/550 W
root@srv020:/usr/lib/nagios/plugins# ./check_idrac -H srv005-idrac -m ./idrac-smiv2.mib -c public -w PS#1 -f check_idrac.conf --volt-warn=0,230 --volt-crit=0,270 --cur-warn=0,1.5 --cur-crit=0,2 --wat-warn=450,800 --wat-crit=400,900
OK - PS 1: OK, Volt I/O: 264 V/0 V, Current: 0.6 A, Watt I/O: 666.0 W/550 W
Even, if I set 0 to min threshold for current, it outputs an error. It's weird...
What do you think?
Regards,
Bruno

**Comment by dangmocrang** [comment]
Hi,

Did you get the latest version 2.0b8? From your checking result I see a
zero voltage output which I just fixed...

About the standby PS I didn't think of this. I will add this case of
checking to next release. Soon.

Regards
Dung

**Comment by bmeneuvrier** [comment]
Dung,
Yes, I'm using 2.0b8. In my previous email, there are 2 checks: PS#1 and PS#2. PS#1 is OK with a zero voltage. PS#2 not. I'm using exactly the same command line (except for #).

Bruno

**Comment by dangmocrang** [comment]
Hi,

My mistake, I add wrong code in 2.0b8 so the Voltage output is not right, It should be other number than zero. I fixed it in 2.0b9

About your standby PS which current is zero, in our idrac I do not see any guide about the standby mode, even the SNMP result does not return value to check PS mode. So could you please send me your snmp data so I can write additional code for this case. Use this command to collect info:

snmpwalk -v2c -c [snmp community] -m [path to my MIB file] powerSupplyTable
snmpwalk -v2c -c [snmp community] -m [path to my MIB file] powerUnitTable

Regards,
Dung

**Comment by bmeneuvrier** [comment]
Hi Dung,
I've updated the plugin with version 2.0b9 and the voltage output is now ok. By the way, it seems you forgot to update the version number in the header of your script. It's still 2.0b8.
Here is the requested information. srv004 and srv005 are the same hardware  (PE R430) with the same settings. Output is OK with srv004 but not with srv005.
root@srv020:/usr/lib/nagios/plugins# snmpwalk -v 2c -c public -m ./idrac-smiv2.mib srv005-idrac powerSupplyTable
IDRAC-MIB-SMIv2::powerSupplychassisIndex.1.1 = INTEGER: 1
IDRAC-MIB-SMIv2::powerSupplychassisIndex.1.2 = INTEGER: 1
IDRAC-MIB-SMIv2::powerSupplyIndex.1.1 = INTEGER: 1
IDRAC-MIB-SMIv2::powerSupplyIndex.1.2 = INTEGER: 2
IDRAC-MIB-SMIv2::powerSupplyStateCapabilitiesUnique.1.1 = INTEGER: 0
IDRAC-MIB-SMIv2::powerSupplyStateCapabilitiesUnique.1.2 = INTEGER: 0
IDRAC-MIB-SMIv2::powerSupplyStateSettingsUnique.1.1 = INTEGER: acPowerAndSwitchAreOnPowerSupplyIsOnIsOkAndOnline(242)
IDRAC-MIB-SMIv2::powerSupplyStateSettingsUnique.1.2 = INTEGER: acPowerAndSwitchAreOnPowerSupplyIsOnIsOkAndOnline(242)
IDRAC-MIB-SMIv2::powerSupplyStatus.1.1 = INTEGER: ok(3)
IDRAC-MIB-SMIv2::powerSupplyStatus.1.2 = INTEGER: ok(3)
IDRAC-MIB-SMIv2::powerSupplyOutputWatts.1.1 = INTEGER: 5500
IDRAC-MIB-SMIv2::powerSupplyOutputWatts.1.2 = INTEGER: 5500
IDRAC-MIB-SMIv2::powerSupplyType.1.1 = INTEGER: powerSupplyTypeIsAC(9)
IDRAC-MIB-SMIv2::powerSupplyType.1.2 = INTEGER: powerSupplyTypeIsAC(9)
IDRAC-MIB-SMIv2::powerSupplyLocationName.1.1 = STRING: "PS1 Status"
IDRAC-MIB-SMIv2::powerSupplyLocationName.1.2 = STRING: "PS2 Status"
IDRAC-MIB-SMIv2::powerSupplyInputVoltage.1.1 = INTEGER: 264
IDRAC-MIB-SMIv2::powerSupplyInputVoltage.1.2 = INTEGER: 264
IDRAC-MIB-SMIv2::powerSupplypowerUnitIndexReference.1.1 = INTEGER: 1
IDRAC-MIB-SMIv2::powerSupplypowerUnitIndexReference.1.2 = INTEGER: 1
IDRAC-MIB-SMIv2::powerSupplySensorState.1.1 = INTEGER: presenceDetected(1)
IDRAC-MIB-SMIv2::powerSupplySensorState.1.2 = INTEGER: presenceDetected(1)
IDRAC-MIB-SMIv2::powerSupplyPowerMonitorCapable.1.1 = INTEGER: 1
IDRAC-MIB-SMIv2::powerSupplyPowerMonitorCapable.1.2 = INTEGER: 1
IDRAC-MIB-SMIv2::powerSupplyRatedInputWattage.1.1 = INTEGER: 6660
IDRAC-MIB-SMIv2::powerSupplyRatedInputWattage.1.2 = INTEGER: 6660
IDRAC-MIB-SMIv2::powerSupplyFQDD.1.1 = STRING: "PSU.Slot.1"
IDRAC-MIB-SMIv2::powerSupplyFQDD.1.2 = STRING: "PSU.Slot.2"
IDRAC-MIB-SMIv2::powerSupplyTableEntry.16.1.1 = INTEGER: 228
IDRAC-MIB-SMIv2::powerSupplyTableEntry.16.1.2 = INTEGER: 230
root@srv020:/usr/lib/nagios/plugins# snmpwalk -v 2c -c public -m ./idrac-smiv2.mib srv005-idrac powerUnitTable
IDRAC-MIB-SMIv2::powerUnitchassisIndex.1.1 = INTEGER: 1
IDRAC-MIB-SMIv2::powerUnitIndex.1.1 = INTEGER: 1
IDRAC-MIB-SMIv2::powerUnitStateCapabilities.1.1 = INTEGER: 0
IDRAC-MIB-SMIv2::powerUnitStateSettings.1.1 = INTEGER: enabled(2)
IDRAC-MIB-SMIv2::powerUnitRedundancyStatus.1.1 = INTEGER: full(3)
IDRAC-MIB-SMIv2::powerSupplyCountForRedundancy.1.1 = INTEGER: 0
IDRAC-MIB-SMIv2::powerUnitName.1.1 = STRING: "System Board PS Redundancy"
IDRAC-MIB-SMIv2::powerUnitStatus.1.1 = INTEGER: ok(3)
root@srv020:/usr/lib/nagios/plugins# snmpwalk -v 2c -c public -m ./idrac-smiv2.mib srv004-idrac powerSupplyTable
IDRAC-MIB-SMIv2::powerSupplychassisIndex.1.1 = INTEGER: 1
IDRAC-MIB-SMIv2::powerSupplychassisIndex.1.2 = INTEGER: 1
IDRAC-MIB-SMIv2::powerSupplyIndex.1.1 = INTEGER: 1
IDRAC-MIB-SMIv2::powerSupplyIndex.1.2 = INTEGER: 2
IDRAC-MIB-SMIv2::powerSupplyStateCapabilitiesUnique.1.1 = INTEGER: 0
IDRAC-MIB-SMIv2::powerSupplyStateCapabilitiesUnique.1.2 = INTEGER: 0
IDRAC-MIB-SMIv2::powerSupplyStateSettingsUnique.1.1 = INTEGER: acPowerAndSwitchAreOnPowerSupplyIsOnIsOkAndOnline(242)
IDRAC-MIB-SMIv2::powerSupplyStateSettingsUnique.1.2 = INTEGER: acPowerAndSwitchAreOnPowerSupplyIsOnIsOkAndOnline(242)
IDRAC-MIB-SMIv2::powerSupplyStatus.1.1 = INTEGER: ok(3)
IDRAC-MIB-SMIv2::powerSupplyStatus.1.2 = INTEGER: ok(3)
IDRAC-MIB-SMIv2::powerSupplyOutputWatts.1.1 = INTEGER: 5500
IDRAC-MIB-SMIv2::powerSupplyOutputWatts.1.2 = INTEGER: 5500
IDRAC-MIB-SMIv2::powerSupplyType.1.1 = INTEGER: powerSupplyTypeIsAC(9)
IDRAC-MIB-SMIv2::powerSupplyType.1.2 = INTEGER: powerSupplyTypeIsAC(9)
IDRAC-MIB-SMIv2::powerSupplyLocationName.1.1 = STRING: "PS1 Status"
IDRAC-MIB-SMIv2::powerSupplyLocationName.1.2 = STRING: "PS2 Status"
IDRAC-MIB-SMIv2::powerSupplyInputVoltage.1.1 = INTEGER: 264
IDRAC-MIB-SMIv2::powerSupplyInputVoltage.1.2 = INTEGER: 264
IDRAC-MIB-SMIv2::powerSupplypowerUnitIndexReference.1.1 = INTEGER: 1
IDRAC-MIB-SMIv2::powerSupplypowerUnitIndexReference.1.2 = INTEGER: 1
IDRAC-MIB-SMIv2::powerSupplySensorState.1.1 = INTEGER: presenceDetected(1)
IDRAC-MIB-SMIv2::powerSupplySensorState.1.2 = INTEGER: presenceDetected(1)
IDRAC-MIB-SMIv2::powerSupplyPowerMonitorCapable.1.1 = INTEGER: 1
IDRAC-MIB-SMIv2::powerSupplyPowerMonitorCapable.1.2 = INTEGER: 1
IDRAC-MIB-SMIv2::powerSupplyRatedInputWattage.1.1 = INTEGER: 6660
IDRAC-MIB-SMIv2::powerSupplyRatedInputWattage.1.2 = INTEGER: 6660
IDRAC-MIB-SMIv2::powerSupplyFQDD.1.1 = STRING: "PSU.Slot.1"
IDRAC-MIB-SMIv2::powerSupplyFQDD.1.2 = STRING: "PSU.Slot.2"
IDRAC-MIB-SMIv2::powerSupplyTableEntry.16.1.1 = INTEGER: 228
IDRAC-MIB-SMIv2::powerSupplyTableEntry.16.1.2 = INTEGER: 230
root@srv020:/usr/lib/nagios/plugins# snmpwalk -v 2c -c public -m ./idrac-smiv2.mib srv004-idrac powerUnitTable
IDRAC-MIB-SMIv2::powerUnitchassisIndex.1.1 = INTEGER: 1
IDRAC-MIB-SMIv2::powerUnitIndex.1.1 = INTEGER: 1
IDRAC-MIB-SMIv2::powerUnitStateCapabilities.1.1 = INTEGER: 0
IDRAC-MIB-SMIv2::powerUnitStateSettings.1.1 = INTEGER: enabled(2)
IDRAC-MIB-SMIv2::powerUnitRedundancyStatus.1.1 = INTEGER: full(3)
IDRAC-MIB-SMIv2::powerSupplyCountForRedundancy.1.1 = INTEGER: 0
IDRAC-MIB-SMIv2::powerUnitName.1.1 = STRING: "System Board PS Redundancy"
IDRAC-MIB-SMIv2::powerUnitStatus.1.1 = INTEGER: ok(3)

Thanks for your help,
Bruno

**Comment by dangmocrang** [comment]
Hi,

SNMP output does not show the "PS" mode, so there is no way to detect if PS is working on standby mode.

 I will find another way to exclude this case :(

Regards,

**Comment by dangmocrang** [comment]
merged with issue#10
https://github.com/dangmocrang/check_idrac/issues/10

**Comment by dangmocrang** [comment]
Hi,

Check out version 2.1. It now supports you to ignore alerting on chosen hardware.

Regards,
Dung

**Comment by dangmocrang** [comment]
Hi Bruno,

Latest version 2.1 supports ignore threshold for chosen hardware as you
wanted.

https://github.com/dangmocrang/check_idrac

Regards,
Dung Nguyen
