### ISSUE TITLE
check a group of 

### ISSUE THREAD

**Issue by barosch78** [dangmocrang/check_idrac#7]
hi,
and thank you for this great plugin!
is it possible to monitor a group of hardware items in the nagios way without a check for every single module?
for example the memory. i use this check
idrac_2.0b9 -H 10.0.1.3 -f check_idrac.conf -p -w MEM
and i get this result:
Memory 1 (DIMM Socket A1) 8.0 GB/1333 MHz: ENABLED/OK [DDR3, Micron Technology, S/N: E09DD683]
Memory 2 (DIMM Socket A2) 8.0 GB/1333 MHz: ENABLED/OK [DDR3, Micron Technology, S/N: E09DD684]
Memory 3 (DIMM Socket A3) 8.0 GB/1333 MHz: ENABLED/OK [DDR3, Micron Technology, S/N: E09DD686]
Memory 4 (DIMM Socket A4) 8.0 GB/1333 MHz: ENABLED/OK [DDR3, Micron Technology, S/N: E09DD685]
Memory 5 (DIMM Socket B1) 8.0 GB/1333 MHz: ENABLED/OK [DDR3, Micron Technology, S/N: E09DD673]
Memory 6 (DIMM Socket B2) 8.0 GB/1333 MHz: ENABLED/OK [DDR3, Micron Technology, S/N: E09DD670]
Memory 7 (DIMM Socket B3) 8.0 GB/1333 MHz: ENABLED/OK [DDR3, Micron Technology, S/N: E09DD67F]
Memory 8 (DIMM Socket B4) 8.0 GB/1333 MHz: ENABLED/OK [DDR3, Micron Technology, S/N: E09DD682]
Memory 9 (DIMM Socket A5) 8.0 GB/1333 MHz: ENABLED/OK [DDR3, Micron Technology, S/N: E09DD583]
Memory 10 (DIMM Socket A6) 8.0 GB/1333 MHz: ENABLED/OK [DDR3, Micron Technology, S/N: E09DD582]
Memory 11 (DIMM Socket A7) 8.0 GB/1333 MHz: ENABLED/OK [DDR3, Micron Technology, S/N: E09DD61F]
Memory 12 (DIMM Socket A8) 8.0 GB/1333 MHz: ENABLED/OK [DDR3, Micron Technology, S/N: E09DD579]
Memory 13 (DIMM Socket B5) 8.0 GB/1333 MHz: ENABLED/OK [DDR3, Micron Technology, S/N: E09DD57F]
Memory 14 (DIMM Socket B6) 8.0 GB/1333 MHz: ENABLED/OK [DDR3, Micron Technology, S/N: E09DD581]
Memory 15 (DIMM Socket B7) 8.0 GB/1333 MHz: ENABLED/OK [DDR3, Micron Technology, S/N: E09DD57E]
Memory 16 (DIMM Socket B8) 8.0 GB/1333 MHz: ENABLED/OK [DDR3, Micron Technology, S/N: E09DD580]
Memory 17 (DIMM Socket A9) 16.0 GB/1600 MHz: ENABLED/OK [DDR3, Samsung, S/N: 01BE535B]
Memory 18 (DIMM Socket A10) 16.0 GB/1600 MHz: ENABLED/OK [DDR3, Samsung, S/N: 01BE575A]
Memory 19 (DIMM Socket A11) 16.0 GB/1600 MHz: ENABLED/OK [DDR3, Samsung, S/N: 01BE570C]
Memory 20 (DIMM Socket A12) 16.0 GB/1600 MHz: ENABLED/OK [DDR3, Samsung, S/N: 01BE5365]
Memory 21 (DIMM Socket B9) 16.0 GB/1600 MHz: ENABLED/OK [DDR3, Samsung, S/N: 01BE533E]
Memory 22 (DIMM Socket B10) 16.0 GB/1600 MHz: ENABLED/OK [DDR3, Samsung, S/N: 01BE534C]
Memory 23 (DIMM Socket B11) 16.0 GB/1600 MHz: ENABLED/OK [DDR3, Samsung, S/N: 01BE57D6]
Memory 24 (DIMM Socket B12) 16.0 GB/1600 MHz: ENABLED/OK [DDR3, Samsung, S/N: 01BE57F6]

checking every module is painful. is it possible to get the global status of all memory modules without checking every single module?
thank you in advance
barosch

**Comment by dangmocrang** [comment]
Hi,

The plugin is not designed to do that. Because compile all things into one check will cause trouble for you when checking and view the monitoring result.

Regards,
Dung

**Comment by barosch78** [comment]
ok.
thank you for the clarification.
greetings
baroch

**Comment by Jcpetrucci** [comment]
Can you please clarify:
When using the group check (not specifying "#" after the hardware) is there a way to make the entire check return warning / critical if a single component of the group is bad?

For example if checking all PSUs and one is bad, the group check seems to return OK when I'd like it to return warning. 

Thank you

**Comment by dangmocrang** [comment]
Hi,

Currently the check is not good support for this kind of check. Sorry 😂
