### ISSUE TITLE
--perf has no effect

### ISSUE THREAD

**Issue by Jcpetrucci** [dangmocrang/check_idrac#8]
[root@REDACTED ~]# /usr/local/nagios/libexec/idrac_2.0b9.py -H REDACTED -c REDACTED -w FAN --perf
System Board Fan1A: 2400 RPM - ENABLED/OK
System Board Fan1B: 1560 RPM - ENABLED/OK
System Board Fan2A: 3720 RPM - ENABLED/OK
System Board Fan2B: 2640 RPM - ENABLED/OK
System Board Fan3A: 2520 RPM - ENABLED/OK
System Board Fan3B: 1800 RPM - ENABLED/OK
System Board Fan4A: 2520 RPM - ENABLED/OK
System Board Fan4B: 1800 RPM - ENABLED/OK
System Board Fan5A: 2400 RPM - ENABLED/OK
System Board Fan5B: 1800 RPM - ENABLED/OK
[root@REDACTED ~]# /usr/local/nagios/libexec/idrac_2.0b9.py -H REDACTED -c REDACTED -w FAN 
System Board Fan1A: 2400 RPM - ENABLED/OK
System Board Fan1B: 1560 RPM - ENABLED/OK
System Board Fan2A: 3720 RPM - ENABLED/OK
System Board Fan2B: 2640 RPM - ENABLED/OK
System Board Fan3A: 2520 RPM - ENABLED/OK
System Board Fan3B: 1800 RPM - ENABLED/OK
System Board Fan4A: 2520 RPM - ENABLED/OK
System Board Fan4B: 1800 RPM - ENABLED/OK
System Board Fan5A: 2400 RPM - ENABLED/OK
System Board Fan5B: 1800 RPM - ENABLED/OK

**Comment by dangmocrang** [comment]
Hi,

You are performing group checking mode so perf has no effect.

Use with -w Fan#1 or 2, 3, etc

Regards,
Dung
